apiVersion: apps/v1                                                             
kind: Deployment
metadata:
  name: bookstore-deployment
  labels:
    app: bookstore
spec: 
  replicas: {{ .Values.image.bookstore.replicas }}
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: {{ .Values.image.bookstore.repository }}:{{ .Values.image.bookstore.tag }}
        ports:
          - containerPort: {{ .Values.service.bookstore.ports.port }}
          - containerPort: {{ .Values.service.bookstoreDebug.ports.port }}
        imagePullPolicy: {{ .Values.image.bookstore.pullPolicy }}
        securityContext:
          privileged: true
        env:
          - name: CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore
  type: {{ .Values.service.bookstore.type }}
  ports:
    - protocol: {{ .Values.service.bookstore.ports.protocol }}
      port: {{ .Values.service.bookstore.ports.port }}
      targetPort: {{ .Values.service.bookstore.ports.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service-debug
spec:
  selector:
    app: bookstore
  type: {{ .Values.service.bookstore.type }}
  ports:
    - protocol: {{ .Values.service.bookstore.ports.protocol }}
      port: {{ .Values.service.bookstoreDebug.ports.port }}
      targetPort: {{ .Values.service.bookstoreDebug.ports.port }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:    
  name: service-bind
roleRef:     
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:    
- kind: ServiceAccount
  name: default
  namespace: default
  