# Default values for bookstore-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  bookstore:
    repository: boknowswiki/bookstore
    pullPolicy: Always
    tag: "v1"
    replicas: 1
  mongo:
    repository: mongo
    replicas: 1

service:
  mongo:
    ports:
      protocol: TCP
      port: 27017
      targetPort: 27017
  bookstore:
    type: LoadBalancer
    ports:
      protocol: TCP
      port: 8888
      targetPort: 8888
  bookstoreDebug:
    type: LoadBalancer
    ports:
      protocol: TCP
      port: 6666
      targetPort: 6666
