# permissions for end users to edit books.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: book-editor-role
rules:
- apiGroups:
  - books.bookstore.com
  resources:
  - books
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - books.bookstore.com
  resources:
  - books/status
  verbs:
  - get
