apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
  labels:
    app: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: boknowswiki/bookstore:v1
        ports:
          - containerPort: 8888
          - containerPort: 6666
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
      #serviceAccountName: service-account
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service-debug
spec:
  selector:
    app: bookstore
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6666
      targetPort: 6666
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:    
  name: service-bind
roleRef:     
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:    
- kind: ServiceAccount
  name: default
  namespace: default
